### PR TITLE
tutorial revision and review process

### LINKED ISSUE #22: [Review] Tutorial 2 MD and Notebook Changes
This issue is dedicated to the changes needed on tutorial 2 to reflect the new authentication for the student.

Tasks

- [x] Add content about terminal commands to the markdown and images
- [x] Fix notebook to reflect a working notebook after usage with those terminal commands
- [x] Change beginning description to make sure that people have to run the terminal commands before running the notebook

### PR DESCRIPTION
**Pull request by harshpavuluri**

### CODE REVIEW

**Comment by harshpavuluri** [comment]
@jialincheoh Give the tutorials a scan before I merge in, just pushed the fixes to the queries and such

**Comment by sbrunswi** [comment]
@harshpavuluri  and @jialincheoh 

- [x] jia to delete her branch
- [x] Jia to review and update harsha branch
- [x] Jia to make all changes to the tutorials if possible directly - if questions come up, they will be commented here
- [x] Jia tries to run notebooks as well (and harsha) 
- [x] Put final tested ones on dev site! 
- [x] Sabine to review on dev and github branch
- [x] Ask Stevens for final review today
- [x] Load tutorials on the lev website asap (tonight)
- [x] Harsha is going to make sure that peope have access to the training datasets @harshpavuluri

**Comment by harshpavuluri** [comment]
> * [ ]  Harsha is going to make sure that peope have access to the training datasets @harshpavuluri

Working through the bugs in "[BUG] Increase key access from 100 users to at least 200](https://github.com/ironhacks/cloud-data-platform/issues/1)"

Update:

Finished that issue. Need to adjust a few things in Tutorial 2

- [ ] Swap command "gcloud auth application-default login" to "gcloud auth login"

**Comment by harshpavuluri** [comment]
Latest commit should have cleared everything. Merging

**Comment by sbrunswi** [comment]
@jialincheoh  - GREAT work. I will be reviewing the tutorials now on the dev site. Can you quickly give instructions what is important to be checked? Thank you.

**Comment by harshpavuluri** [comment]
> @jialincheoh - GREAT work. I will be reviewing the tutorials now on the dev site. Can you quickly give instructions what is important to be checked? Thank you.

Tutorial 2 links and making sure that all the tables for the code segments an such look good as well. Quick scan of the content as well to make sure that it all looks good. Typos and grammar should be good as well, but never a harm to check it again.

**Comment by jialincheoh** [comment]
@aronlindberg @crystalhappycat , would u mind reviewing the tutorials and put your comments here 

Dev site - https://dev.ironhacks.com/admin/hacks/LR77BPhLNgXHNN6AajIS/tutorials

**Comment by crystalhappycat** [comment]
Formulas don't load:https://dev.ironhacks.com/hacks/fall-22-dev-hack/tutorials/HfYdj2cIi8Rmwfu0HEX0
Example design doesn't load: https://dev.ironhacks.com/hacks/fall-22-dev-hack/tutorials/mc7KGXYL0veeM4z85dXG
We didn't include all the summary examples in 6b? https://dev.ironhacks.com/hacks/fall-22-dev-hack/tutorials/LtjgTOPogWALncdw07oE

**Comment by jialincheoh** [comment]
These are all addressed @crystalhappycat , thanks for comments.

**Pull request merged**
